// Code generated by Prisma (prisma@1.34.10). DO NOT EDIT.
// Please don't change this file manually but run `prisma generate` to update it.
// For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

import { DocumentNode } from "graphql";
import {
  makePrismaClientClass,
  BaseClientOptions,
  Model
} from "prisma-client-lib";
import { typeDefs } from "./prisma-schema";

export type AtLeastOne<T, U = { [K in keyof T]: Pick<T, K> }> = Partial<T> &
  U[keyof U];

export type Maybe<T> = T | undefined | null;

export interface Exists {
  follow: (where?: FollowWhereInput) => Promise<boolean>;
  notes: (where?: NotesWhereInput) => Promise<boolean>;
  user: (where?: UserWhereInput) => Promise<boolean>;
}

export interface Node {}

export type FragmentableArray<T> = Promise<Array<T>> & Fragmentable;

export interface Fragmentable {
  $fragment<T>(fragment: string | DocumentNode): Promise<T>;
}

export interface Prisma {
  $exists: Exists;
  $graphql: <T = any>(
    query: string,
    variables?: { [key: string]: any }
  ) => Promise<T>;

  /**
   * Queries
   */

  follow: (where: FollowWhereUniqueInput) => FollowNullablePromise;
  follows: (args?: {
    where?: FollowWhereInput;
    orderBy?: FollowOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Follow>;
  followsConnection: (args?: {
    where?: FollowWhereInput;
    orderBy?: FollowOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FollowConnectionPromise;
  notes: (where: NotesWhereUniqueInput) => NotesNullablePromise;
  noteses: (args?: {
    where?: NotesWhereInput;
    orderBy?: NotesOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<Notes>;
  notesesConnection: (args?: {
    where?: NotesWhereInput;
    orderBy?: NotesOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => NotesConnectionPromise;
  user: (where: UserWhereUniqueInput) => UserNullablePromise;
  users: (args?: {
    where?: UserWhereInput;
    orderBy?: UserOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => FragmentableArray<User>;
  usersConnection: (args?: {
    where?: UserWhereInput;
    orderBy?: UserOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => UserConnectionPromise;
  node: (args: { id: ID_Output }) => Node;

  /**
   * Mutations
   */

  createFollow: (data: FollowCreateInput) => FollowPromise;
  updateFollow: (args: {
    data: FollowUpdateInput;
    where: FollowWhereUniqueInput;
  }) => FollowPromise;
  updateManyFollows: (args: {
    data: FollowUpdateManyMutationInput;
    where?: FollowWhereInput;
  }) => BatchPayloadPromise;
  upsertFollow: (args: {
    where: FollowWhereUniqueInput;
    create: FollowCreateInput;
    update: FollowUpdateInput;
  }) => FollowPromise;
  deleteFollow: (where: FollowWhereUniqueInput) => FollowPromise;
  deleteManyFollows: (where?: FollowWhereInput) => BatchPayloadPromise;
  createNotes: (data: NotesCreateInput) => NotesPromise;
  updateNotes: (args: {
    data: NotesUpdateInput;
    where: NotesWhereUniqueInput;
  }) => NotesPromise;
  updateManyNoteses: (args: {
    data: NotesUpdateManyMutationInput;
    where?: NotesWhereInput;
  }) => BatchPayloadPromise;
  upsertNotes: (args: {
    where: NotesWhereUniqueInput;
    create: NotesCreateInput;
    update: NotesUpdateInput;
  }) => NotesPromise;
  deleteNotes: (where: NotesWhereUniqueInput) => NotesPromise;
  deleteManyNoteses: (where?: NotesWhereInput) => BatchPayloadPromise;
  createUser: (data: UserCreateInput) => UserPromise;
  updateUser: (args: {
    data: UserUpdateInput;
    where: UserWhereUniqueInput;
  }) => UserPromise;
  updateManyUsers: (args: {
    data: UserUpdateManyMutationInput;
    where?: UserWhereInput;
  }) => BatchPayloadPromise;
  upsertUser: (args: {
    where: UserWhereUniqueInput;
    create: UserCreateInput;
    update: UserUpdateInput;
  }) => UserPromise;
  deleteUser: (where: UserWhereUniqueInput) => UserPromise;
  deleteManyUsers: (where?: UserWhereInput) => BatchPayloadPromise;

  /**
   * Subscriptions
   */

  $subscribe: Subscription;
}

export interface Subscription {
  follow: (
    where?: FollowSubscriptionWhereInput
  ) => FollowSubscriptionPayloadSubscription;
  notes: (
    where?: NotesSubscriptionWhereInput
  ) => NotesSubscriptionPayloadSubscription;
  user: (
    where?: UserSubscriptionWhereInput
  ) => UserSubscriptionPayloadSubscription;
}

export interface ClientConstructor<T> {
  new (options?: BaseClientOptions): T;
}

/**
 * Types
 */

export type FollowOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "githubID_ASC"
  | "githubID_DESC";

export type NotesOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "title_ASC"
  | "title_DESC"
  | "body_ASC"
  | "body_DESC";

export type UserOrderByInput =
  | "id_ASC"
  | "id_DESC"
  | "githubID_ASC"
  | "githubID_DESC";

export type MutationType = "CREATED" | "UPDATED" | "DELETED";

export type FollowWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
  githubID?: Maybe<String>;
}>;

export interface FollowWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  followed?: Maybe<UserWhereInput>;
  githubID?: Maybe<String>;
  githubID_not?: Maybe<String>;
  githubID_in?: Maybe<String[] | String>;
  githubID_not_in?: Maybe<String[] | String>;
  githubID_lt?: Maybe<String>;
  githubID_lte?: Maybe<String>;
  githubID_gt?: Maybe<String>;
  githubID_gte?: Maybe<String>;
  githubID_contains?: Maybe<String>;
  githubID_not_contains?: Maybe<String>;
  githubID_starts_with?: Maybe<String>;
  githubID_not_starts_with?: Maybe<String>;
  githubID_ends_with?: Maybe<String>;
  githubID_not_ends_with?: Maybe<String>;
  notes_every?: Maybe<NotesWhereInput>;
  notes_some?: Maybe<NotesWhereInput>;
  notes_none?: Maybe<NotesWhereInput>;
  AND?: Maybe<FollowWhereInput[] | FollowWhereInput>;
  OR?: Maybe<FollowWhereInput[] | FollowWhereInput>;
  NOT?: Maybe<FollowWhereInput[] | FollowWhereInput>;
}

export interface UserWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  githubID?: Maybe<String>;
  githubID_not?: Maybe<String>;
  githubID_in?: Maybe<String[] | String>;
  githubID_not_in?: Maybe<String[] | String>;
  githubID_lt?: Maybe<String>;
  githubID_lte?: Maybe<String>;
  githubID_gt?: Maybe<String>;
  githubID_gte?: Maybe<String>;
  githubID_contains?: Maybe<String>;
  githubID_not_contains?: Maybe<String>;
  githubID_starts_with?: Maybe<String>;
  githubID_not_starts_with?: Maybe<String>;
  githubID_ends_with?: Maybe<String>;
  githubID_not_ends_with?: Maybe<String>;
  following_every?: Maybe<FollowWhereInput>;
  following_some?: Maybe<FollowWhereInput>;
  following_none?: Maybe<FollowWhereInput>;
  AND?: Maybe<UserWhereInput[] | UserWhereInput>;
  OR?: Maybe<UserWhereInput[] | UserWhereInput>;
  NOT?: Maybe<UserWhereInput[] | UserWhereInput>;
}

export interface NotesWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  for?: Maybe<FollowWhereInput>;
  title?: Maybe<String>;
  title_not?: Maybe<String>;
  title_in?: Maybe<String[] | String>;
  title_not_in?: Maybe<String[] | String>;
  title_lt?: Maybe<String>;
  title_lte?: Maybe<String>;
  title_gt?: Maybe<String>;
  title_gte?: Maybe<String>;
  title_contains?: Maybe<String>;
  title_not_contains?: Maybe<String>;
  title_starts_with?: Maybe<String>;
  title_not_starts_with?: Maybe<String>;
  title_ends_with?: Maybe<String>;
  title_not_ends_with?: Maybe<String>;
  body?: Maybe<String>;
  body_not?: Maybe<String>;
  body_in?: Maybe<String[] | String>;
  body_not_in?: Maybe<String[] | String>;
  body_lt?: Maybe<String>;
  body_lte?: Maybe<String>;
  body_gt?: Maybe<String>;
  body_gte?: Maybe<String>;
  body_contains?: Maybe<String>;
  body_not_contains?: Maybe<String>;
  body_starts_with?: Maybe<String>;
  body_not_starts_with?: Maybe<String>;
  body_ends_with?: Maybe<String>;
  body_not_ends_with?: Maybe<String>;
  AND?: Maybe<NotesWhereInput[] | NotesWhereInput>;
  OR?: Maybe<NotesWhereInput[] | NotesWhereInput>;
  NOT?: Maybe<NotesWhereInput[] | NotesWhereInput>;
}

export type NotesWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
}>;

export type UserWhereUniqueInput = AtLeastOne<{
  id: Maybe<ID_Input>;
  githubID?: Maybe<String>;
}>;

export interface FollowCreateInput {
  id?: Maybe<ID_Input>;
  followed: UserCreateOneWithoutFollowingInput;
  githubID: String;
  notes?: Maybe<NotesCreateManyWithoutForInput>;
}

export interface UserCreateOneWithoutFollowingInput {
  create?: Maybe<UserCreateWithoutFollowingInput>;
  connect?: Maybe<UserWhereUniqueInput>;
}

export interface UserCreateWithoutFollowingInput {
  id?: Maybe<ID_Input>;
  githubID: String;
}

export interface NotesCreateManyWithoutForInput {
  create?: Maybe<NotesCreateWithoutForInput[] | NotesCreateWithoutForInput>;
  connect?: Maybe<NotesWhereUniqueInput[] | NotesWhereUniqueInput>;
}

export interface NotesCreateWithoutForInput {
  id?: Maybe<ID_Input>;
  title: String;
  body: String;
}

export interface FollowUpdateInput {
  followed?: Maybe<UserUpdateOneRequiredWithoutFollowingInput>;
  githubID?: Maybe<String>;
  notes?: Maybe<NotesUpdateManyWithoutForInput>;
}

export interface UserUpdateOneRequiredWithoutFollowingInput {
  create?: Maybe<UserCreateWithoutFollowingInput>;
  update?: Maybe<UserUpdateWithoutFollowingDataInput>;
  upsert?: Maybe<UserUpsertWithoutFollowingInput>;
  connect?: Maybe<UserWhereUniqueInput>;
}

export interface UserUpdateWithoutFollowingDataInput {
  githubID?: Maybe<String>;
}

export interface UserUpsertWithoutFollowingInput {
  update: UserUpdateWithoutFollowingDataInput;
  create: UserCreateWithoutFollowingInput;
}

export interface NotesUpdateManyWithoutForInput {
  create?: Maybe<NotesCreateWithoutForInput[] | NotesCreateWithoutForInput>;
  delete?: Maybe<NotesWhereUniqueInput[] | NotesWhereUniqueInput>;
  connect?: Maybe<NotesWhereUniqueInput[] | NotesWhereUniqueInput>;
  set?: Maybe<NotesWhereUniqueInput[] | NotesWhereUniqueInput>;
  disconnect?: Maybe<NotesWhereUniqueInput[] | NotesWhereUniqueInput>;
  update?: Maybe<
    | NotesUpdateWithWhereUniqueWithoutForInput[]
    | NotesUpdateWithWhereUniqueWithoutForInput
  >;
  upsert?: Maybe<
    | NotesUpsertWithWhereUniqueWithoutForInput[]
    | NotesUpsertWithWhereUniqueWithoutForInput
  >;
  deleteMany?: Maybe<NotesScalarWhereInput[] | NotesScalarWhereInput>;
  updateMany?: Maybe<
    NotesUpdateManyWithWhereNestedInput[] | NotesUpdateManyWithWhereNestedInput
  >;
}

export interface NotesUpdateWithWhereUniqueWithoutForInput {
  where: NotesWhereUniqueInput;
  data: NotesUpdateWithoutForDataInput;
}

export interface NotesUpdateWithoutForDataInput {
  title?: Maybe<String>;
  body?: Maybe<String>;
}

export interface NotesUpsertWithWhereUniqueWithoutForInput {
  where: NotesWhereUniqueInput;
  update: NotesUpdateWithoutForDataInput;
  create: NotesCreateWithoutForInput;
}

export interface NotesScalarWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  title?: Maybe<String>;
  title_not?: Maybe<String>;
  title_in?: Maybe<String[] | String>;
  title_not_in?: Maybe<String[] | String>;
  title_lt?: Maybe<String>;
  title_lte?: Maybe<String>;
  title_gt?: Maybe<String>;
  title_gte?: Maybe<String>;
  title_contains?: Maybe<String>;
  title_not_contains?: Maybe<String>;
  title_starts_with?: Maybe<String>;
  title_not_starts_with?: Maybe<String>;
  title_ends_with?: Maybe<String>;
  title_not_ends_with?: Maybe<String>;
  body?: Maybe<String>;
  body_not?: Maybe<String>;
  body_in?: Maybe<String[] | String>;
  body_not_in?: Maybe<String[] | String>;
  body_lt?: Maybe<String>;
  body_lte?: Maybe<String>;
  body_gt?: Maybe<String>;
  body_gte?: Maybe<String>;
  body_contains?: Maybe<String>;
  body_not_contains?: Maybe<String>;
  body_starts_with?: Maybe<String>;
  body_not_starts_with?: Maybe<String>;
  body_ends_with?: Maybe<String>;
  body_not_ends_with?: Maybe<String>;
  AND?: Maybe<NotesScalarWhereInput[] | NotesScalarWhereInput>;
  OR?: Maybe<NotesScalarWhereInput[] | NotesScalarWhereInput>;
  NOT?: Maybe<NotesScalarWhereInput[] | NotesScalarWhereInput>;
}

export interface NotesUpdateManyWithWhereNestedInput {
  where: NotesScalarWhereInput;
  data: NotesUpdateManyDataInput;
}

export interface NotesUpdateManyDataInput {
  title?: Maybe<String>;
  body?: Maybe<String>;
}

export interface FollowUpdateManyMutationInput {
  githubID?: Maybe<String>;
}

export interface NotesCreateInput {
  id?: Maybe<ID_Input>;
  for: FollowCreateOneWithoutNotesInput;
  title: String;
  body: String;
}

export interface FollowCreateOneWithoutNotesInput {
  create?: Maybe<FollowCreateWithoutNotesInput>;
  connect?: Maybe<FollowWhereUniqueInput>;
}

export interface FollowCreateWithoutNotesInput {
  id?: Maybe<ID_Input>;
  followed: UserCreateOneWithoutFollowingInput;
  githubID: String;
}

export interface NotesUpdateInput {
  for?: Maybe<FollowUpdateOneRequiredWithoutNotesInput>;
  title?: Maybe<String>;
  body?: Maybe<String>;
}

export interface FollowUpdateOneRequiredWithoutNotesInput {
  create?: Maybe<FollowCreateWithoutNotesInput>;
  update?: Maybe<FollowUpdateWithoutNotesDataInput>;
  upsert?: Maybe<FollowUpsertWithoutNotesInput>;
  connect?: Maybe<FollowWhereUniqueInput>;
}

export interface FollowUpdateWithoutNotesDataInput {
  followed?: Maybe<UserUpdateOneRequiredWithoutFollowingInput>;
  githubID?: Maybe<String>;
}

export interface FollowUpsertWithoutNotesInput {
  update: FollowUpdateWithoutNotesDataInput;
  create: FollowCreateWithoutNotesInput;
}

export interface NotesUpdateManyMutationInput {
  title?: Maybe<String>;
  body?: Maybe<String>;
}

export interface UserCreateInput {
  id?: Maybe<ID_Input>;
  githubID: String;
  following?: Maybe<FollowCreateManyWithoutFollowedInput>;
}

export interface FollowCreateManyWithoutFollowedInput {
  create?: Maybe<
    FollowCreateWithoutFollowedInput[] | FollowCreateWithoutFollowedInput
  >;
  connect?: Maybe<FollowWhereUniqueInput[] | FollowWhereUniqueInput>;
}

export interface FollowCreateWithoutFollowedInput {
  id?: Maybe<ID_Input>;
  githubID: String;
  notes?: Maybe<NotesCreateManyWithoutForInput>;
}

export interface UserUpdateInput {
  githubID?: Maybe<String>;
  following?: Maybe<FollowUpdateManyWithoutFollowedInput>;
}

export interface FollowUpdateManyWithoutFollowedInput {
  create?: Maybe<
    FollowCreateWithoutFollowedInput[] | FollowCreateWithoutFollowedInput
  >;
  delete?: Maybe<FollowWhereUniqueInput[] | FollowWhereUniqueInput>;
  connect?: Maybe<FollowWhereUniqueInput[] | FollowWhereUniqueInput>;
  set?: Maybe<FollowWhereUniqueInput[] | FollowWhereUniqueInput>;
  disconnect?: Maybe<FollowWhereUniqueInput[] | FollowWhereUniqueInput>;
  update?: Maybe<
    | FollowUpdateWithWhereUniqueWithoutFollowedInput[]
    | FollowUpdateWithWhereUniqueWithoutFollowedInput
  >;
  upsert?: Maybe<
    | FollowUpsertWithWhereUniqueWithoutFollowedInput[]
    | FollowUpsertWithWhereUniqueWithoutFollowedInput
  >;
  deleteMany?: Maybe<FollowScalarWhereInput[] | FollowScalarWhereInput>;
  updateMany?: Maybe<
    | FollowUpdateManyWithWhereNestedInput[]
    | FollowUpdateManyWithWhereNestedInput
  >;
}

export interface FollowUpdateWithWhereUniqueWithoutFollowedInput {
  where: FollowWhereUniqueInput;
  data: FollowUpdateWithoutFollowedDataInput;
}

export interface FollowUpdateWithoutFollowedDataInput {
  githubID?: Maybe<String>;
  notes?: Maybe<NotesUpdateManyWithoutForInput>;
}

export interface FollowUpsertWithWhereUniqueWithoutFollowedInput {
  where: FollowWhereUniqueInput;
  update: FollowUpdateWithoutFollowedDataInput;
  create: FollowCreateWithoutFollowedInput;
}

export interface FollowScalarWhereInput {
  id?: Maybe<ID_Input>;
  id_not?: Maybe<ID_Input>;
  id_in?: Maybe<ID_Input[] | ID_Input>;
  id_not_in?: Maybe<ID_Input[] | ID_Input>;
  id_lt?: Maybe<ID_Input>;
  id_lte?: Maybe<ID_Input>;
  id_gt?: Maybe<ID_Input>;
  id_gte?: Maybe<ID_Input>;
  id_contains?: Maybe<ID_Input>;
  id_not_contains?: Maybe<ID_Input>;
  id_starts_with?: Maybe<ID_Input>;
  id_not_starts_with?: Maybe<ID_Input>;
  id_ends_with?: Maybe<ID_Input>;
  id_not_ends_with?: Maybe<ID_Input>;
  githubID?: Maybe<String>;
  githubID_not?: Maybe<String>;
  githubID_in?: Maybe<String[] | String>;
  githubID_not_in?: Maybe<String[] | String>;
  githubID_lt?: Maybe<String>;
  githubID_lte?: Maybe<String>;
  githubID_gt?: Maybe<String>;
  githubID_gte?: Maybe<String>;
  githubID_contains?: Maybe<String>;
  githubID_not_contains?: Maybe<String>;
  githubID_starts_with?: Maybe<String>;
  githubID_not_starts_with?: Maybe<String>;
  githubID_ends_with?: Maybe<String>;
  githubID_not_ends_with?: Maybe<String>;
  AND?: Maybe<FollowScalarWhereInput[] | FollowScalarWhereInput>;
  OR?: Maybe<FollowScalarWhereInput[] | FollowScalarWhereInput>;
  NOT?: Maybe<FollowScalarWhereInput[] | FollowScalarWhereInput>;
}

export interface FollowUpdateManyWithWhereNestedInput {
  where: FollowScalarWhereInput;
  data: FollowUpdateManyDataInput;
}

export interface FollowUpdateManyDataInput {
  githubID?: Maybe<String>;
}

export interface UserUpdateManyMutationInput {
  githubID?: Maybe<String>;
}

export interface FollowSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<FollowWhereInput>;
  AND?: Maybe<FollowSubscriptionWhereInput[] | FollowSubscriptionWhereInput>;
  OR?: Maybe<FollowSubscriptionWhereInput[] | FollowSubscriptionWhereInput>;
  NOT?: Maybe<FollowSubscriptionWhereInput[] | FollowSubscriptionWhereInput>;
}

export interface NotesSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<NotesWhereInput>;
  AND?: Maybe<NotesSubscriptionWhereInput[] | NotesSubscriptionWhereInput>;
  OR?: Maybe<NotesSubscriptionWhereInput[] | NotesSubscriptionWhereInput>;
  NOT?: Maybe<NotesSubscriptionWhereInput[] | NotesSubscriptionWhereInput>;
}

export interface UserSubscriptionWhereInput {
  mutation_in?: Maybe<MutationType[] | MutationType>;
  updatedFields_contains?: Maybe<String>;
  updatedFields_contains_every?: Maybe<String[] | String>;
  updatedFields_contains_some?: Maybe<String[] | String>;
  node?: Maybe<UserWhereInput>;
  AND?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>;
  OR?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>;
  NOT?: Maybe<UserSubscriptionWhereInput[] | UserSubscriptionWhereInput>;
}

export interface NodeNode {
  id: ID_Output;
}

export interface Follow {
  id: ID_Output;
  githubID: String;
}

export interface FollowPromise extends Promise<Follow>, Fragmentable {
  id: () => Promise<ID_Output>;
  followed: <T = UserPromise>() => T;
  githubID: () => Promise<String>;
  notes: <T = FragmentableArray<Notes>>(args?: {
    where?: NotesWhereInput;
    orderBy?: NotesOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
}

export interface FollowSubscription
  extends Promise<AsyncIterator<Follow>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  followed: <T = UserSubscription>() => T;
  githubID: () => Promise<AsyncIterator<String>>;
  notes: <T = Promise<AsyncIterator<NotesSubscription>>>(args?: {
    where?: NotesWhereInput;
    orderBy?: NotesOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
}

export interface FollowNullablePromise
  extends Promise<Follow | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  followed: <T = UserPromise>() => T;
  githubID: () => Promise<String>;
  notes: <T = FragmentableArray<Notes>>(args?: {
    where?: NotesWhereInput;
    orderBy?: NotesOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
}

export interface User {
  id: ID_Output;
  githubID: String;
}

export interface UserPromise extends Promise<User>, Fragmentable {
  id: () => Promise<ID_Output>;
  githubID: () => Promise<String>;
  following: <T = FragmentableArray<Follow>>(args?: {
    where?: FollowWhereInput;
    orderBy?: FollowOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
}

export interface UserSubscription
  extends Promise<AsyncIterator<User>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  githubID: () => Promise<AsyncIterator<String>>;
  following: <T = Promise<AsyncIterator<FollowSubscription>>>(args?: {
    where?: FollowWhereInput;
    orderBy?: FollowOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
}

export interface UserNullablePromise
  extends Promise<User | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  githubID: () => Promise<String>;
  following: <T = FragmentableArray<Follow>>(args?: {
    where?: FollowWhereInput;
    orderBy?: FollowOrderByInput;
    skip?: Int;
    after?: String;
    before?: String;
    first?: Int;
    last?: Int;
  }) => T;
}

export interface Notes {
  id: ID_Output;
  title: String;
  body: String;
}

export interface NotesPromise extends Promise<Notes>, Fragmentable {
  id: () => Promise<ID_Output>;
  for: <T = FollowPromise>() => T;
  title: () => Promise<String>;
  body: () => Promise<String>;
}

export interface NotesSubscription
  extends Promise<AsyncIterator<Notes>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  for: <T = FollowSubscription>() => T;
  title: () => Promise<AsyncIterator<String>>;
  body: () => Promise<AsyncIterator<String>>;
}

export interface NotesNullablePromise
  extends Promise<Notes | null>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  for: <T = FollowPromise>() => T;
  title: () => Promise<String>;
  body: () => Promise<String>;
}

export interface FollowConnection {
  pageInfo: PageInfo;
  edges: FollowEdge[];
}

export interface FollowConnectionPromise
  extends Promise<FollowConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<FollowEdge>>() => T;
  aggregate: <T = AggregateFollowPromise>() => T;
}

export interface FollowConnectionSubscription
  extends Promise<AsyncIterator<FollowConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<FollowEdgeSubscription>>>() => T;
  aggregate: <T = AggregateFollowSubscription>() => T;
}

export interface PageInfo {
  hasNextPage: Boolean;
  hasPreviousPage: Boolean;
  startCursor?: String;
  endCursor?: String;
}

export interface PageInfoPromise extends Promise<PageInfo>, Fragmentable {
  hasNextPage: () => Promise<Boolean>;
  hasPreviousPage: () => Promise<Boolean>;
  startCursor: () => Promise<String>;
  endCursor: () => Promise<String>;
}

export interface PageInfoSubscription
  extends Promise<AsyncIterator<PageInfo>>,
    Fragmentable {
  hasNextPage: () => Promise<AsyncIterator<Boolean>>;
  hasPreviousPage: () => Promise<AsyncIterator<Boolean>>;
  startCursor: () => Promise<AsyncIterator<String>>;
  endCursor: () => Promise<AsyncIterator<String>>;
}

export interface FollowEdge {
  node: Follow;
  cursor: String;
}

export interface FollowEdgePromise extends Promise<FollowEdge>, Fragmentable {
  node: <T = FollowPromise>() => T;
  cursor: () => Promise<String>;
}

export interface FollowEdgeSubscription
  extends Promise<AsyncIterator<FollowEdge>>,
    Fragmentable {
  node: <T = FollowSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateFollow {
  count: Int;
}

export interface AggregateFollowPromise
  extends Promise<AggregateFollow>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateFollowSubscription
  extends Promise<AsyncIterator<AggregateFollow>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface NotesConnection {
  pageInfo: PageInfo;
  edges: NotesEdge[];
}

export interface NotesConnectionPromise
  extends Promise<NotesConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<NotesEdge>>() => T;
  aggregate: <T = AggregateNotesPromise>() => T;
}

export interface NotesConnectionSubscription
  extends Promise<AsyncIterator<NotesConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<NotesEdgeSubscription>>>() => T;
  aggregate: <T = AggregateNotesSubscription>() => T;
}

export interface NotesEdge {
  node: Notes;
  cursor: String;
}

export interface NotesEdgePromise extends Promise<NotesEdge>, Fragmentable {
  node: <T = NotesPromise>() => T;
  cursor: () => Promise<String>;
}

export interface NotesEdgeSubscription
  extends Promise<AsyncIterator<NotesEdge>>,
    Fragmentable {
  node: <T = NotesSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateNotes {
  count: Int;
}

export interface AggregateNotesPromise
  extends Promise<AggregateNotes>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateNotesSubscription
  extends Promise<AsyncIterator<AggregateNotes>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface UserConnection {
  pageInfo: PageInfo;
  edges: UserEdge[];
}

export interface UserConnectionPromise
  extends Promise<UserConnection>,
    Fragmentable {
  pageInfo: <T = PageInfoPromise>() => T;
  edges: <T = FragmentableArray<UserEdge>>() => T;
  aggregate: <T = AggregateUserPromise>() => T;
}

export interface UserConnectionSubscription
  extends Promise<AsyncIterator<UserConnection>>,
    Fragmentable {
  pageInfo: <T = PageInfoSubscription>() => T;
  edges: <T = Promise<AsyncIterator<UserEdgeSubscription>>>() => T;
  aggregate: <T = AggregateUserSubscription>() => T;
}

export interface UserEdge {
  node: User;
  cursor: String;
}

export interface UserEdgePromise extends Promise<UserEdge>, Fragmentable {
  node: <T = UserPromise>() => T;
  cursor: () => Promise<String>;
}

export interface UserEdgeSubscription
  extends Promise<AsyncIterator<UserEdge>>,
    Fragmentable {
  node: <T = UserSubscription>() => T;
  cursor: () => Promise<AsyncIterator<String>>;
}

export interface AggregateUser {
  count: Int;
}

export interface AggregateUserPromise
  extends Promise<AggregateUser>,
    Fragmentable {
  count: () => Promise<Int>;
}

export interface AggregateUserSubscription
  extends Promise<AsyncIterator<AggregateUser>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Int>>;
}

export interface BatchPayload {
  count: Long;
}

export interface BatchPayloadPromise
  extends Promise<BatchPayload>,
    Fragmentable {
  count: () => Promise<Long>;
}

export interface BatchPayloadSubscription
  extends Promise<AsyncIterator<BatchPayload>>,
    Fragmentable {
  count: () => Promise<AsyncIterator<Long>>;
}

export interface FollowSubscriptionPayload {
  mutation: MutationType;
  node: Follow;
  updatedFields: String[];
  previousValues: FollowPreviousValues;
}

export interface FollowSubscriptionPayloadPromise
  extends Promise<FollowSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = FollowPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = FollowPreviousValuesPromise>() => T;
}

export interface FollowSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<FollowSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = FollowSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = FollowPreviousValuesSubscription>() => T;
}

export interface FollowPreviousValues {
  id: ID_Output;
  githubID: String;
}

export interface FollowPreviousValuesPromise
  extends Promise<FollowPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  githubID: () => Promise<String>;
}

export interface FollowPreviousValuesSubscription
  extends Promise<AsyncIterator<FollowPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  githubID: () => Promise<AsyncIterator<String>>;
}

export interface NotesSubscriptionPayload {
  mutation: MutationType;
  node: Notes;
  updatedFields: String[];
  previousValues: NotesPreviousValues;
}

export interface NotesSubscriptionPayloadPromise
  extends Promise<NotesSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = NotesPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = NotesPreviousValuesPromise>() => T;
}

export interface NotesSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<NotesSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = NotesSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = NotesPreviousValuesSubscription>() => T;
}

export interface NotesPreviousValues {
  id: ID_Output;
  title: String;
  body: String;
}

export interface NotesPreviousValuesPromise
  extends Promise<NotesPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  title: () => Promise<String>;
  body: () => Promise<String>;
}

export interface NotesPreviousValuesSubscription
  extends Promise<AsyncIterator<NotesPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  title: () => Promise<AsyncIterator<String>>;
  body: () => Promise<AsyncIterator<String>>;
}

export interface UserSubscriptionPayload {
  mutation: MutationType;
  node: User;
  updatedFields: String[];
  previousValues: UserPreviousValues;
}

export interface UserSubscriptionPayloadPromise
  extends Promise<UserSubscriptionPayload>,
    Fragmentable {
  mutation: () => Promise<MutationType>;
  node: <T = UserPromise>() => T;
  updatedFields: () => Promise<String[]>;
  previousValues: <T = UserPreviousValuesPromise>() => T;
}

export interface UserSubscriptionPayloadSubscription
  extends Promise<AsyncIterator<UserSubscriptionPayload>>,
    Fragmentable {
  mutation: () => Promise<AsyncIterator<MutationType>>;
  node: <T = UserSubscription>() => T;
  updatedFields: () => Promise<AsyncIterator<String[]>>;
  previousValues: <T = UserPreviousValuesSubscription>() => T;
}

export interface UserPreviousValues {
  id: ID_Output;
  githubID: String;
}

export interface UserPreviousValuesPromise
  extends Promise<UserPreviousValues>,
    Fragmentable {
  id: () => Promise<ID_Output>;
  githubID: () => Promise<String>;
}

export interface UserPreviousValuesSubscription
  extends Promise<AsyncIterator<UserPreviousValues>>,
    Fragmentable {
  id: () => Promise<AsyncIterator<ID_Output>>;
  githubID: () => Promise<AsyncIterator<String>>;
}

/*
The `ID` scalar type represents a unique identifier, often used to refetch an object or as key for a cache. The ID type appears in a JSON response as a String; however, it is not intended to be human-readable. When expected as an input type, any string (such as `"4"`) or integer (such as `4`) input value will be accepted as an ID.
*/
export type ID_Input = string | number;
export type ID_Output = string;

/*
The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.
*/
export type String = string;

/*
The `Int` scalar type represents non-fractional signed whole numeric values. Int can represent values between -(2^31) and 2^31 - 1.
*/
export type Int = number;

/*
The `Boolean` scalar type represents `true` or `false`.
*/
export type Boolean = boolean;

export type Long = string;

/**
 * Model Metadata
 */

export const models: Model[] = [
  {
    name: "User",
    embedded: false
  },
  {
    name: "Follow",
    embedded: false
  },
  {
    name: "Notes",
    embedded: false
  }
];

/**
 * Type Defs
 */

export const Prisma = makePrismaClientClass<ClientConstructor<Prisma>>({
  typeDefs,
  models,
  endpoint: `${process.env["PRISMA"]}`,
  secret: `${process.env["SECRET"]}`
});
export const prisma = new Prisma();
