// Code generated by Prisma (prisma@1.34.10). DO NOT EDIT.
  // Please don't change this file manually but run `prisma generate` to update it.
  // For more information, please read the docs: https://www.prisma.io/docs/prisma-client/

export const typeDefs = /* GraphQL */ `type AggregateFollow {
  count: Int!
}

type AggregateNote {
  count: Int!
}

type AggregateUser {
  count: Int!
}

type BatchPayload {
  count: Long!
}

type Follow {
  id: ID!
  followed: User!
  githubID: String!
  notes(where: NoteWhereInput, orderBy: NoteOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Note!]
}

type FollowConnection {
  pageInfo: PageInfo!
  edges: [FollowEdge]!
  aggregate: AggregateFollow!
}

input FollowCreateInput {
  id: ID
  followed: UserCreateOneWithoutFollowingInput!
  githubID: String!
  notes: NoteCreateManyWithoutForInput
}

input FollowCreateManyWithoutFollowedInput {
  create: [FollowCreateWithoutFollowedInput!]
  connect: [FollowWhereUniqueInput!]
}

input FollowCreateOneWithoutNotesInput {
  create: FollowCreateWithoutNotesInput
  connect: FollowWhereUniqueInput
}

input FollowCreateWithoutFollowedInput {
  id: ID
  githubID: String!
  notes: NoteCreateManyWithoutForInput
}

input FollowCreateWithoutNotesInput {
  id: ID
  followed: UserCreateOneWithoutFollowingInput!
  githubID: String!
}

type FollowEdge {
  node: Follow!
  cursor: String!
}

enum FollowOrderByInput {
  id_ASC
  id_DESC
  githubID_ASC
  githubID_DESC
}

type FollowPreviousValues {
  id: ID!
  githubID: String!
}

input FollowScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  githubID: String
  githubID_not: String
  githubID_in: [String!]
  githubID_not_in: [String!]
  githubID_lt: String
  githubID_lte: String
  githubID_gt: String
  githubID_gte: String
  githubID_contains: String
  githubID_not_contains: String
  githubID_starts_with: String
  githubID_not_starts_with: String
  githubID_ends_with: String
  githubID_not_ends_with: String
  AND: [FollowScalarWhereInput!]
  OR: [FollowScalarWhereInput!]
  NOT: [FollowScalarWhereInput!]
}

type FollowSubscriptionPayload {
  mutation: MutationType!
  node: Follow
  updatedFields: [String!]
  previousValues: FollowPreviousValues
}

input FollowSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: FollowWhereInput
  AND: [FollowSubscriptionWhereInput!]
  OR: [FollowSubscriptionWhereInput!]
  NOT: [FollowSubscriptionWhereInput!]
}

input FollowUpdateInput {
  followed: UserUpdateOneRequiredWithoutFollowingInput
  githubID: String
  notes: NoteUpdateManyWithoutForInput
}

input FollowUpdateManyDataInput {
  githubID: String
}

input FollowUpdateManyMutationInput {
  githubID: String
}

input FollowUpdateManyWithoutFollowedInput {
  create: [FollowCreateWithoutFollowedInput!]
  delete: [FollowWhereUniqueInput!]
  connect: [FollowWhereUniqueInput!]
  set: [FollowWhereUniqueInput!]
  disconnect: [FollowWhereUniqueInput!]
  update: [FollowUpdateWithWhereUniqueWithoutFollowedInput!]
  upsert: [FollowUpsertWithWhereUniqueWithoutFollowedInput!]
  deleteMany: [FollowScalarWhereInput!]
  updateMany: [FollowUpdateManyWithWhereNestedInput!]
}

input FollowUpdateManyWithWhereNestedInput {
  where: FollowScalarWhereInput!
  data: FollowUpdateManyDataInput!
}

input FollowUpdateOneRequiredWithoutNotesInput {
  create: FollowCreateWithoutNotesInput
  update: FollowUpdateWithoutNotesDataInput
  upsert: FollowUpsertWithoutNotesInput
  connect: FollowWhereUniqueInput
}

input FollowUpdateWithoutFollowedDataInput {
  githubID: String
  notes: NoteUpdateManyWithoutForInput
}

input FollowUpdateWithoutNotesDataInput {
  followed: UserUpdateOneRequiredWithoutFollowingInput
  githubID: String
}

input FollowUpdateWithWhereUniqueWithoutFollowedInput {
  where: FollowWhereUniqueInput!
  data: FollowUpdateWithoutFollowedDataInput!
}

input FollowUpsertWithoutNotesInput {
  update: FollowUpdateWithoutNotesDataInput!
  create: FollowCreateWithoutNotesInput!
}

input FollowUpsertWithWhereUniqueWithoutFollowedInput {
  where: FollowWhereUniqueInput!
  update: FollowUpdateWithoutFollowedDataInput!
  create: FollowCreateWithoutFollowedInput!
}

input FollowWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  followed: UserWhereInput
  githubID: String
  githubID_not: String
  githubID_in: [String!]
  githubID_not_in: [String!]
  githubID_lt: String
  githubID_lte: String
  githubID_gt: String
  githubID_gte: String
  githubID_contains: String
  githubID_not_contains: String
  githubID_starts_with: String
  githubID_not_starts_with: String
  githubID_ends_with: String
  githubID_not_ends_with: String
  notes_every: NoteWhereInput
  notes_some: NoteWhereInput
  notes_none: NoteWhereInput
  AND: [FollowWhereInput!]
  OR: [FollowWhereInput!]
  NOT: [FollowWhereInput!]
}

input FollowWhereUniqueInput {
  id: ID
  githubID: String
}

scalar Long

type Mutation {
  createFollow(data: FollowCreateInput!): Follow!
  updateFollow(data: FollowUpdateInput!, where: FollowWhereUniqueInput!): Follow
  updateManyFollows(data: FollowUpdateManyMutationInput!, where: FollowWhereInput): BatchPayload!
  upsertFollow(where: FollowWhereUniqueInput!, create: FollowCreateInput!, update: FollowUpdateInput!): Follow!
  deleteFollow(where: FollowWhereUniqueInput!): Follow
  deleteManyFollows(where: FollowWhereInput): BatchPayload!
  createNote(data: NoteCreateInput!): Note!
  updateNote(data: NoteUpdateInput!, where: NoteWhereUniqueInput!): Note
  updateManyNotes(data: NoteUpdateManyMutationInput!, where: NoteWhereInput): BatchPayload!
  upsertNote(where: NoteWhereUniqueInput!, create: NoteCreateInput!, update: NoteUpdateInput!): Note!
  deleteNote(where: NoteWhereUniqueInput!): Note
  deleteManyNotes(where: NoteWhereInput): BatchPayload!
  createUser(data: UserCreateInput!): User!
  updateUser(data: UserUpdateInput!, where: UserWhereUniqueInput!): User
  updateManyUsers(data: UserUpdateManyMutationInput!, where: UserWhereInput): BatchPayload!
  upsertUser(where: UserWhereUniqueInput!, create: UserCreateInput!, update: UserUpdateInput!): User!
  deleteUser(where: UserWhereUniqueInput!): User
  deleteManyUsers(where: UserWhereInput): BatchPayload!
}

enum MutationType {
  CREATED
  UPDATED
  DELETED
}

interface Node {
  id: ID!
}

type Note {
  id: ID!
  for: Follow!
  title: String!
  body: String!
}

type NoteConnection {
  pageInfo: PageInfo!
  edges: [NoteEdge]!
  aggregate: AggregateNote!
}

input NoteCreateInput {
  id: ID
  for: FollowCreateOneWithoutNotesInput!
  title: String!
  body: String!
}

input NoteCreateManyWithoutForInput {
  create: [NoteCreateWithoutForInput!]
  connect: [NoteWhereUniqueInput!]
}

input NoteCreateWithoutForInput {
  id: ID
  title: String!
  body: String!
}

type NoteEdge {
  node: Note!
  cursor: String!
}

enum NoteOrderByInput {
  id_ASC
  id_DESC
  title_ASC
  title_DESC
  body_ASC
  body_DESC
}

type NotePreviousValues {
  id: ID!
  title: String!
  body: String!
}

input NoteScalarWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  title: String
  title_not: String
  title_in: [String!]
  title_not_in: [String!]
  title_lt: String
  title_lte: String
  title_gt: String
  title_gte: String
  title_contains: String
  title_not_contains: String
  title_starts_with: String
  title_not_starts_with: String
  title_ends_with: String
  title_not_ends_with: String
  body: String
  body_not: String
  body_in: [String!]
  body_not_in: [String!]
  body_lt: String
  body_lte: String
  body_gt: String
  body_gte: String
  body_contains: String
  body_not_contains: String
  body_starts_with: String
  body_not_starts_with: String
  body_ends_with: String
  body_not_ends_with: String
  AND: [NoteScalarWhereInput!]
  OR: [NoteScalarWhereInput!]
  NOT: [NoteScalarWhereInput!]
}

type NoteSubscriptionPayload {
  mutation: MutationType!
  node: Note
  updatedFields: [String!]
  previousValues: NotePreviousValues
}

input NoteSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: NoteWhereInput
  AND: [NoteSubscriptionWhereInput!]
  OR: [NoteSubscriptionWhereInput!]
  NOT: [NoteSubscriptionWhereInput!]
}

input NoteUpdateInput {
  for: FollowUpdateOneRequiredWithoutNotesInput
  title: String
  body: String
}

input NoteUpdateManyDataInput {
  title: String
  body: String
}

input NoteUpdateManyMutationInput {
  title: String
  body: String
}

input NoteUpdateManyWithoutForInput {
  create: [NoteCreateWithoutForInput!]
  delete: [NoteWhereUniqueInput!]
  connect: [NoteWhereUniqueInput!]
  set: [NoteWhereUniqueInput!]
  disconnect: [NoteWhereUniqueInput!]
  update: [NoteUpdateWithWhereUniqueWithoutForInput!]
  upsert: [NoteUpsertWithWhereUniqueWithoutForInput!]
  deleteMany: [NoteScalarWhereInput!]
  updateMany: [NoteUpdateManyWithWhereNestedInput!]
}

input NoteUpdateManyWithWhereNestedInput {
  where: NoteScalarWhereInput!
  data: NoteUpdateManyDataInput!
}

input NoteUpdateWithoutForDataInput {
  title: String
  body: String
}

input NoteUpdateWithWhereUniqueWithoutForInput {
  where: NoteWhereUniqueInput!
  data: NoteUpdateWithoutForDataInput!
}

input NoteUpsertWithWhereUniqueWithoutForInput {
  where: NoteWhereUniqueInput!
  update: NoteUpdateWithoutForDataInput!
  create: NoteCreateWithoutForInput!
}

input NoteWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  for: FollowWhereInput
  title: String
  title_not: String
  title_in: [String!]
  title_not_in: [String!]
  title_lt: String
  title_lte: String
  title_gt: String
  title_gte: String
  title_contains: String
  title_not_contains: String
  title_starts_with: String
  title_not_starts_with: String
  title_ends_with: String
  title_not_ends_with: String
  body: String
  body_not: String
  body_in: [String!]
  body_not_in: [String!]
  body_lt: String
  body_lte: String
  body_gt: String
  body_gte: String
  body_contains: String
  body_not_contains: String
  body_starts_with: String
  body_not_starts_with: String
  body_ends_with: String
  body_not_ends_with: String
  AND: [NoteWhereInput!]
  OR: [NoteWhereInput!]
  NOT: [NoteWhereInput!]
}

input NoteWhereUniqueInput {
  id: ID
}

type PageInfo {
  hasNextPage: Boolean!
  hasPreviousPage: Boolean!
  startCursor: String
  endCursor: String
}

type Query {
  follow(where: FollowWhereUniqueInput!): Follow
  follows(where: FollowWhereInput, orderBy: FollowOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Follow]!
  followsConnection(where: FollowWhereInput, orderBy: FollowOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): FollowConnection!
  note(where: NoteWhereUniqueInput!): Note
  notes(where: NoteWhereInput, orderBy: NoteOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Note]!
  notesConnection(where: NoteWhereInput, orderBy: NoteOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): NoteConnection!
  user(where: UserWhereUniqueInput!): User
  users(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [User]!
  usersConnection(where: UserWhereInput, orderBy: UserOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): UserConnection!
  node(id: ID!): Node
}

type Subscription {
  follow(where: FollowSubscriptionWhereInput): FollowSubscriptionPayload
  note(where: NoteSubscriptionWhereInput): NoteSubscriptionPayload
  user(where: UserSubscriptionWhereInput): UserSubscriptionPayload
}

type User {
  id: ID!
  githubID: String!
  following(where: FollowWhereInput, orderBy: FollowOrderByInput, skip: Int, after: String, before: String, first: Int, last: Int): [Follow!]
}

type UserConnection {
  pageInfo: PageInfo!
  edges: [UserEdge]!
  aggregate: AggregateUser!
}

input UserCreateInput {
  id: ID
  githubID: String!
  following: FollowCreateManyWithoutFollowedInput
}

input UserCreateOneWithoutFollowingInput {
  create: UserCreateWithoutFollowingInput
  connect: UserWhereUniqueInput
}

input UserCreateWithoutFollowingInput {
  id: ID
  githubID: String!
}

type UserEdge {
  node: User!
  cursor: String!
}

enum UserOrderByInput {
  id_ASC
  id_DESC
  githubID_ASC
  githubID_DESC
}

type UserPreviousValues {
  id: ID!
  githubID: String!
}

type UserSubscriptionPayload {
  mutation: MutationType!
  node: User
  updatedFields: [String!]
  previousValues: UserPreviousValues
}

input UserSubscriptionWhereInput {
  mutation_in: [MutationType!]
  updatedFields_contains: String
  updatedFields_contains_every: [String!]
  updatedFields_contains_some: [String!]
  node: UserWhereInput
  AND: [UserSubscriptionWhereInput!]
  OR: [UserSubscriptionWhereInput!]
  NOT: [UserSubscriptionWhereInput!]
}

input UserUpdateInput {
  githubID: String
  following: FollowUpdateManyWithoutFollowedInput
}

input UserUpdateManyMutationInput {
  githubID: String
}

input UserUpdateOneRequiredWithoutFollowingInput {
  create: UserCreateWithoutFollowingInput
  update: UserUpdateWithoutFollowingDataInput
  upsert: UserUpsertWithoutFollowingInput
  connect: UserWhereUniqueInput
}

input UserUpdateWithoutFollowingDataInput {
  githubID: String
}

input UserUpsertWithoutFollowingInput {
  update: UserUpdateWithoutFollowingDataInput!
  create: UserCreateWithoutFollowingInput!
}

input UserWhereInput {
  id: ID
  id_not: ID
  id_in: [ID!]
  id_not_in: [ID!]
  id_lt: ID
  id_lte: ID
  id_gt: ID
  id_gte: ID
  id_contains: ID
  id_not_contains: ID
  id_starts_with: ID
  id_not_starts_with: ID
  id_ends_with: ID
  id_not_ends_with: ID
  githubID: String
  githubID_not: String
  githubID_in: [String!]
  githubID_not_in: [String!]
  githubID_lt: String
  githubID_lte: String
  githubID_gt: String
  githubID_gte: String
  githubID_contains: String
  githubID_not_contains: String
  githubID_starts_with: String
  githubID_not_starts_with: String
  githubID_ends_with: String
  githubID_not_ends_with: String
  following_every: FollowWhereInput
  following_some: FollowWhereInput
  following_none: FollowWhereInput
  AND: [UserWhereInput!]
  OR: [UserWhereInput!]
  NOT: [UserWhereInput!]
}

input UserWhereUniqueInput {
  id: ID
  githubID: String
}
`